-- V13: Seed all 192 topics across 10 modules
INSERT INTO topics (id, slug, title, subtitle, module_id, difficulty, estimated_minutes, display_order, content_status, completion_percentage, is_active) VALUES
-- MODULE 1: Spring Framework Fundamentals (1-19)
(1, 'what-is-spring', 'What is Spring?', 'Introduction to Spring Framework ecosystem', 1, 'BEGINNER', 15, 1, 'DRAFT', 0, true),
(2, 'problems-before-spring', 'Problems before Spring', 'EJB complexity and corporate challenges', 1, 'BEGINNER', 20, 2, 'DRAFT', 0, true),
(3, 'why-spring-framework', 'Why Spring Framework?', 'Key benefits and core philosophies of Spring', 1, 'BEGINNER', 15, 3, 'DRAFT', 0, true),
(4, 'spring-architecture', 'Spring Architecture', 'Layered architecture overview', 1, 'INTERMEDIATE', 20, 4, 'DRAFT', 0, true),
(5, 'spring-modules', 'Spring Modules', 'Core, AOP, Web, Data, and Integration modules', 1, 'BEGINNER', 15, 5, 'DRAFT', 0, true),
(6, 'ioc', 'IOC (Inversion of Control)', 'Conceptual shift of control from programmer to framework', 1, 'BEGINNER', 20, 6, 'DRAFT', 0, true),
(7, 'ioc-container', 'IOC Container', 'The heart of Spring runtime engine', 1, 'INTERMEDIATE', 25, 7, 'DRAFT', 0, true),
(8, 'bean-factory', 'BeanFactory', 'Low-level configuration and lazy bean loading container', 1, 'INTERMEDIATE', 20, 8, 'DRAFT', 0, true),
(9, 'application-context', 'ApplicationContext', 'High-level container with event publishing and internationalization', 1, 'INTERMEDIATE', 25, 9, 'DRAFT', 0, true),
(10, 'dependency-injection', 'Dependency Injection', 'Implementing IOC through dependency supply patterns', 1, 'BEGINNER', 20, 10, 'DRAFT', 0, true),
(11, 'constructor-injection', 'Constructor Injection', 'Best practice for final immutable dependencies', 1, 'BEGINNER', 15, 11, 'DRAFT', 0, true),
(12, 'setter-injection', 'Setter Injection', 'Optional and mutable dependency injection', 1, 'BEGINNER', 15, 12, 'DRAFT', 0, true),
(13, 'field-injection', 'Field Injection', 'Direct injection via reflection and why it should be avoided', 1, 'INTERMEDIATE', 15, 13, 'DRAFT', 0, true),
(14, 'bean', 'Spring Bean', 'Definition of Java objects managed by the Spring container', 1, 'BEGINNER', 15, 14, 'DRAFT', 0, true),
(15, 'bean-scope', 'Bean Scope', 'Lifecycle scopes (Singleton, Prototype, Request, Session, etc.)', 1, 'INTERMEDIATE', 25, 15, 'DRAFT', 0, true),
(16, 'bean-lifecycle', 'Bean Lifecycle', 'Callbacks, Initialization, and Destruction stages', 1, 'ADVANCED', 30, 16, 'DRAFT', 0, true),
(17, 'component-scanning', 'Component Scanning', 'Classpath scanning for stereotype annotations', 1, 'BEGINNER', 15, 17, 'DRAFT', 0, true),
(18, 'reflection-in-spring', 'Reflection in Spring', 'How Spring inspects metadata and annotations at runtime', 1, 'ADVANCED', 25, 18, 'DRAFT', 0, true),
(19, 'spring-container-internal-working', 'Spring Container Internal Working', 'Step-by-step startup, bean post-processing, and dependency resolution', 1, 'EXPERT', 40, 19, 'DRAFT', 0, true),

-- MODULE 2: Spring Boot (20-35)
(20, 'what-is-spring-boot', 'What is Spring Boot?', 'Opinionated extension of Spring Framework', 2, 'BEGINNER', 15, 1, 'DRAFT', 0, true),
(21, 'spring-vs-spring-boot', 'Spring vs Spring Boot', 'Direct comparison of configuration and setup', 2, 'BEGINNER', 15, 2, 'DRAFT', 0, true),
(22, 'why-spring-boot', 'Why Spring Boot?', 'Speeding up development with default conventions', 2, 'BEGINNER', 15, 3, 'DRAFT', 0, true),
(23, 'spring-boot-architecture', 'Spring Boot Architecture', 'Starters, Autoconfigure, Actuator, and CLI layers', 2, 'INTERMEDIATE', 20, 4, 'DRAFT', 0, true),
(24, 'spring-boot-startup-flow', 'Spring Boot Startup Flow', 'Bootstrap, environment preparation, context loading, and runner execution', 2, 'ADVANCED', 30, 5, 'DRAFT', 0, true),
(25, 'spring-boot-application', '@SpringBootApplication', 'Analysis of @Configuration, @EnableAutoConfiguration, and @ComponentScan', 2, 'INTERMEDIATE', 20, 6, 'DRAFT', 0, true),
(26, 'auto-configuration', 'Auto Configuration', 'Spring Boot conditional bean loading internals', 2, 'ADVANCED', 25, 7, 'DRAFT', 0, true),
(27, 'starter-dependencies', 'Starter Dependencies', 'Maven dependency aggregation and parent POM management', 2, 'BEGINNER', 15, 8, 'DRAFT', 0, true),
(28, 'embedded-tomcat', 'Embedded Tomcat', 'Web server packaging and runtime execution in standalone jar', 2, 'INTERMEDIATE', 15, 9, 'DRAFT', 0, true),
(29, 'spring-initializr', 'Spring Initializr', 'Project scaffolding and dependency configuration tool', 2, 'BEGINNER', 10, 10, 'DRAFT', 0, true),
(30, 'application-properties', 'application.properties', 'Property-based external configuration', 2, 'BEGINNER', 15, 11, 'DRAFT', 0, true),
(31, 'application-yml', 'application.yml', 'YAML-based hierarchical configuration and nesting', 2, 'BEGINNER', 15, 12, 'DRAFT', 0, true),
(32, 'profiles', 'Profiles', 'Environment-specific configuration separation (dev, prod, test)', 2, 'INTERMEDIATE', 20, 13, 'DRAFT', 0, true),
(33, 'spring-boot-actuator', 'Spring Boot Actuator', 'Production monitoring, metrics, healthchecks, and thread dumps', 2, 'ADVANCED', 25, 14, 'DRAFT', 0, true),
(34, 'command-line-runner', 'CommandLineRunner', 'Executing custom startup tasks using string arrays', 2, 'INTERMEDIATE', 15, 15, 'DRAFT', 0, true),
(35, 'application-runner', 'ApplicationRunner', 'Executing custom startup tasks using ApplicationArguments', 2, 'INTERMEDIATE', 15, 16, 'DRAFT', 0, true),

-- MODULE 3: Spring Boot Annotations (36-61)
(36, 'component', '@Component', 'Generic stereotype annotation for Spring-managed beans', 3, 'BEGINNER', 15, 1, 'DRAFT', 0, true),
(37, 'service', '@Service', 'Stereotype for business layer logic and transaction boundaries', 3, 'BEGINNER', 15, 2, 'DRAFT', 0, true),
(38, 'repository', '@Repository', 'Stereotype for data access layer with automatic exception translation', 3, 'BEGINNER', 15, 3, 'DRAFT', 0, true),
(39, 'controller', '@Controller', 'Stereotype for Spring MVC view-rendering web layer', 3, 'BEGINNER', 15, 4, 'DRAFT', 0, true),
(40, 'rest-controller', '@RestController', 'Combining @Controller and @ResponseBody for REST APIs', 3, 'BEGINNER', 15, 5, 'DRAFT', 0, true),
(41, 'autowired', '@Autowired', 'Automatic dependency injection matching by type', 3, 'BEGINNER', 15, 6, 'DRAFT', 0, true),
(42, 'configuration', '@Configuration', 'Class-level definition for Java-based Spring configuration', 3, 'INTERMEDIATE', 20, 7, 'DRAFT', 0, true),
(43, 'bean-annotation', '@Bean', 'Method-level registration of a Spring-managed bean', 3, 'INTERMEDIATE', 20, 8, 'DRAFT', 0, true),
(44, 'primary', '@Primary', 'Resolving autowire ambiguity by defining default candidate', 3, 'BEGINNER', 15, 9, 'DRAFT', 0, true),
(45, 'qualifier', '@Qualifier', 'Fine-grained control of dependency injection by bean name', 3, 'INTERMEDIATE', 15, 10, 'DRAFT', 0, true),
(46, 'value', '@Value', 'Injecting values from properties, files, and SpEL expressions', 3, 'BEGINNER', 20, 11, 'DRAFT', 0, true),
(47, 'property-source', '@PropertySource', 'Loading external property files into Spring environment', 3, 'INTERMEDIATE', 15, 12, 'DRAFT', 0, true),
(48, 'component-scan', '@ComponentScan', 'Explicit package scanning configuration', 3, 'INTERMEDIATE', 15, 13, 'DRAFT', 0, true),
(49, 'request-mapping', '@RequestMapping', 'Routing web requests to specific controller handler methods', 3, 'BEGINNER', 20, 14, 'DRAFT', 0, true),
(50, 'get-mapping', '@GetMapping', 'Shortcut for @RequestMapping for GET requests', 3, 'BEGINNER', 10, 15, 'DRAFT', 0, true),
(51, 'post-mapping', '@PostMapping', 'Shortcut for @RequestMapping for POST requests', 3, 'BEGINNER', 10, 16, 'DRAFT', 0, true),
(52, 'put-mapping', '@PutMapping', 'Shortcut for @RequestMapping for PUT requests', 3, 'BEGINNER', 10, 17, 'DRAFT', 0, true),
(53, 'delete-mapping', '@DeleteMapping', 'Shortcut for @RequestMapping for DELETE requests', 3, 'BEGINNER', 10, 18, 'DRAFT', 0, true),
(54, 'path-variable', '@PathVariable', 'Extracting parameters directly from URI path templates', 3, 'BEGINNER', 15, 19, 'DRAFT', 0, true),
(55, 'request-param', '@RequestParam', 'Extracting query parameters and form fields from request', 3, 'BEGINNER', 15, 20, 'DRAFT', 0, true),
(56, 'request-body', '@RequestBody', 'Deserializing JSON body into Java objects using HttpMessageConverter', 3, 'INTERMEDIATE', 20, 21, 'DRAFT', 0, true),
(57, 'response-body', '@ResponseBody', 'Serializing controller return objects directly into HTTP response body', 3, 'INTERMEDIATE', 15, 22, 'DRAFT', 0, true),
(58, 'response-status', '@ResponseStatus', 'Mapping controller results or exceptions to HTTP status codes', 3, 'BEGINNER', 15, 23, 'DRAFT', 0, true),
(59, 'exception-handler', '@ExceptionHandler', 'Declaring controller-local custom exception handlers', 3, 'INTERMEDIATE', 20, 24, 'DRAFT', 0, true),
(60, 'controller-advice', '@ControllerAdvice', 'Centralizing exception handling and data binding globally', 3, 'ADVANCED', 25, 25, 'DRAFT', 0, true),
(61, 'rest-controller-advice', '@RestControllerAdvice', 'Specialized @ControllerAdvice with @ResponseBody enabled by default', 3, 'ADVANCED', 20, 26, 'DRAFT', 0, true),

-- MODULE 4: Microservices (62-85)
(62, 'what-are-microservices', 'What are Microservices?', 'Decoupled, independent, and domain-driven architectures', 4, 'BEGINNER', 20, 1, 'DRAFT', 0, true),
(63, 'why-microservices', 'Why Microservices?', 'Solving scale, deployment, and team organization bottlenecks', 4, 'BEGINNER', 15, 2, 'DRAFT', 0, true),
(64, 'monolith-vs-microservices', 'Monolith vs Microservices', 'Comparison of codebases, databases, deployments, and trade-offs', 4, 'BEGINNER', 20, 3, 'DRAFT', 0, true),
(65, 'service-discovery', 'Service Discovery', 'Solving dynamic IP lookup in ephemeral container environments', 4, 'INTERMEDIATE', 25, 4, 'DRAFT', 0, true),
(66, 'eureka', 'Netflix Eureka Discovery Server', 'Implementing registry and heartbeat checks in Spring Cloud', 4, 'INTERMEDIATE', 25, 5, 'DRAFT', 0, true),
(67, 'api-gateway', 'API Gateway', 'Reverse proxy, routing, filtering, rate limiting, and security hub', 4, 'ADVANCED', 30, 6, 'DRAFT', 0, true),
(68, 'load-balancer', 'Load Balancer', 'Client-side load balancing with Spring Cloud LoadBalancer', 4, 'INTERMEDIATE', 20, 7, 'DRAFT', 0, true),
(69, 'configuration-server', 'Configuration Server', 'Centralized configuration storage with Git backends', 4, 'ADVANCED', 25, 8, 'DRAFT', 0, true),
(70, 'inter-service-communication', 'Inter-Service Communication', 'Synchronous vs Asynchronous microservice interaction', 4, 'INTERMEDIATE', 25, 9, 'DRAFT', 0, true),
(71, 'feign-client', 'Declarative Feign Client', 'Writing type-safe REST clients using interfaces and annotations', 4, 'INTERMEDIATE', 20, 10, 'DRAFT', 0, true),
(72, 'rest-template', 'RestTemplate', 'Blocking synchronous client for HTTP calls', 4, 'BEGINNER', 15, 11, 'DRAFT', 0, true),
(73, 'web-client', 'WebClient', 'Non-blocking reactive client for modern HTTP calls', 4, 'ADVANCED', 25, 12, 'DRAFT', 0, true),
(74, 'kafka', 'Apache Kafka', 'Distributed log, event streaming, partitions, and consumer groups', 4, 'ADVANCED', 35, 13, 'DRAFT', 0, true),
(75, 'rabbit-mq', 'RabbitMQ', 'AMQP message broker with exchanges, bindings, and queues', 4, 'INTERMEDIATE', 25, 14, 'DRAFT', 0, true),
(76, 'docker', 'Docker Containers', 'Packaging software into portable, predictable container images', 4, 'BEGINNER', 20, 15, 'DRAFT', 0, true),
(77, 'kubernetes', 'Kubernetes Orchestration', 'Managing pods, services, deployments, configmaps, and ingress', 4, 'EXPERT', 40, 16, 'DRAFT', 0, true),
(78, 'circuit-breaker', 'Circuit Breaker Pattern', 'Preventing cascading failures using Resilience4j states', 4, 'ADVANCED', 30, 17, 'DRAFT', 0, true),
(79, 'distributed-transactions', 'Distributed Transactions', 'Challenges of managing transactions across multiple databases', 4, 'EXPERT', 30, 18, 'DRAFT', 0, true),
(80, 'saga-pattern', 'Saga Pattern', 'Orchestration and Choreography systems for eventual consistency', 4, 'EXPERT', 35, 19, 'DRAFT', 0, true),
(81, 'logging', 'Centralized Logging', 'Aggregating logs using ELK Stack or Grafana Loki', 4, 'ADVANCED', 25, 20, 'DRAFT', 0, true),
(82, 'monitoring', 'Prometheus & Grafana', 'Scraping metrics, visualizing JVM dashboards, and alert configs', 4, 'ADVANCED', 25, 21, 'DRAFT', 0, true),
(83, 'distributed-tracing', 'Distributed Tracing', 'Tracking requests across network boundaries with OpenTelemetry/Zipkin', 4, 'ADVANCED', 25, 22, 'DRAFT', 0, true),
(84, 'deployment', 'Deployment Strategies', 'Blue-Green, Canary, Rolling updates, and GitOps', 4, 'ADVANCED', 30, 23, 'DRAFT', 0, true),
(85, 'scaling', 'Autoscaling', 'Horizontal vs Vertical scaling, HPA in Kubernetes, database replica scaling', 4, 'EXPERT', 30, 24, 'DRAFT', 0, true),

-- MODULE 5: Java Collections (86-111)
(86, 'list', 'List Interface', 'Ordered collections containing duplicate elements', 5, 'BEGINNER', 15, 1, 'DRAFT', 0, true),
(87, 'set', 'Set Interface', 'Collections containing unique elements and mathematical sets', 5, 'BEGINNER', 15, 2, 'DRAFT', 0, true),
(88, 'queue', 'Queue Interface', 'FIFO, LIFO, and priority-based elements processing', 5, 'BEGINNER', 15, 3, 'DRAFT', 0, true),
(89, 'map', 'Map Interface', 'Key-value mapping associations', 5, 'BEGINNER', 15, 4, 'DRAFT', 0, true),
(90, 'array-list', 'ArrayList', 'Dynamic resizing arrays, random access, and capacity management', 5, 'BEGINNER', 20, 5, 'DRAFT', 0, true),
(91, 'linked-list', 'LinkedList', 'Doubly-linked nodes list, quick insertions/deletions', 5, 'INTERMEDIATE', 20, 6, 'DRAFT', 0, true),
(92, 'vector', 'Vector', 'Thread-safe dynamic array legacy collection', 5, 'BEGINNER', 15, 7, 'DRAFT', 0, true),
(93, 'stack', 'Stack', 'LIFO legacy collection extending Vector', 5, 'BEGINNER', 15, 8, 'DRAFT', 0, true),
(94, 'hash-set', 'HashSet', 'Hashtable-backed unique elements storage', 5, 'BEGINNER', 15, 9, 'DRAFT', 0, true),
(95, 'linked-hash-set', 'LinkedHashSet', 'Insertion-ordered unique elements storage', 5, 'INTERMEDIATE', 15, 10, 'DRAFT', 0, true),
(96, 'tree-set', 'TreeSet', 'Sorted unique elements backed by Red-Black tree', 5, 'INTERMEDIATE', 20, 11, 'DRAFT', 0, true),
(97, 'priority-queue', 'PriorityQueue', 'Unbounded heap queue, ordering via natural sort or comparator', 5, 'INTERMEDIATE', 20, 12, 'DRAFT', 0, true),
(98, 'hash-map', 'HashMap', 'Key-value store based on hashing, node list to balanced tree transition', 5, 'INTERMEDIATE', 30, 13, 'DRAFT', 0, true),
(99, 'linked-hash-map', 'LinkedHashMap', 'Insertion or access-ordered key-value store, LRU cache backing', 5, 'INTERMEDIATE', 20, 14, 'DRAFT', 0, true),
(100, 'tree-map', 'TreeMap', 'Navigable map sorted by natural key order or Comparator', 5, 'INTERMEDIATE', 20, 15, 'DRAFT', 0, true),
(101, 'hashtable', 'Hashtable', 'Synchronized key-value legacy map, zero null values rule', 5, 'BEGINNER', 15, 16, 'DRAFT', 0, true),
(102, 'concurrent-hash-map', 'ConcurrentHashMap', 'Thread-safe map with segment locks and lock-free reads', 5, 'ADVANCED', 30, 17, 'DRAFT', 0, true),
(103, 'fail-fast', 'Fail-Fast Iterators', 'ModCount based quick failure detection on structural modification', 5, 'INTERMEDIATE', 20, 18, 'DRAFT', 0, true),
(104, 'fail-safe', 'Fail-Safe Iterators', 'Working on copied arrays/segments, concurrency protection', 5, 'INTERMEDIATE', 20, 19, 'DRAFT', 0, true),
(105, 'comparable', 'Comparable Interface', 'Defining natural order sorting for user classes via compareTo()', 5, 'BEGINNER', 15, 20, 'DRAFT', 0, true),
(106, 'comparator', 'Comparator Interface', 'Creating multiple external sorting strategies via compare()', 5, 'BEGINNER', 15, 21, 'DRAFT', 0, true),
(107, 'hash-collision', 'Hash Collision', 'Handling same hashCode keys with chaining (linked nodes) and Red-Black tree conversion', 5, 'ADVANCED', 25, 22, 'DRAFT', 0, true),
(108, 'load-factor', 'Load Factor', 'Threshold for sizing hash collections, defaults, and trade-offs', 5, 'INTERMEDIATE', 15, 23, 'DRAFT', 0, true),
(109, 'rehashing', 'Rehashing Mechanism', 'Sizing array capacity up, rebuilding hashes, and cost performance', 5, 'ADVANCED', 20, 24, 'DRAFT', 0, true),
(110, 'collections-internal-working', 'Collections Internal Working', 'Memory layouts, node structures, and reference references', 5, 'ADVANCED', 25, 25, 'DRAFT', 0, true),
(111, 'time-complexity', 'Collections Time Complexity', 'Big-O performance index of lists, sets, maps for reads, writes, searches', 5, 'INTERMEDIATE', 20, 26, 'DRAFT', 0, true),

-- MODULE 6: Java 8, 17, 21 (112-124)
(112, 'lambda', 'Lambda Expressions', 'Inline functional interface syntax', 6, 'BEGINNER', 15, 1, 'DRAFT', 0, true),
(113, 'stream-api', 'Stream API', 'Declarative data pipelines with map, filter, reduce, collect operations', 6, 'INTERMEDIATE', 25, 2, 'DRAFT', 0, true),
(114, 'functional-interface', 'Functional Interfaces', 'SAM interfaces (@FunctionalInterface, Predicate, Consumer, Function, Supplier)', 6, 'BEGINNER', 20, 3, 'DRAFT', 0, true),
(115, 'method-reference', 'Method Reference', 'Typing shortcut for lambdas referencing existing class/object methods', 6, 'BEGINNER', 10, 4, 'DRAFT', 0, true),
(116, 'optional', 'Optional Container', 'Nullable wrapper preventing NullPointerExceptions', 6, 'BEGINNER', 15, 5, 'DRAFT', 0, true),
(117, 'date-time-api', 'Date-Time API', 'Immutable, thread-safe temporal package (java.time)', 6, 'BEGINNER', 15, 6, 'DRAFT', 0, true),
(118, 'parallel-streams', 'Parallel Streams', 'ForkJoinPool-backed parallel collection pipelines', 6, 'INTERMEDIATE', 20, 7, 'DRAFT', 0, true),
(119, 'java-17-features', 'Java 17 Features', 'Sealed classes, Pattern matching instanceOf, Text Blocks', 6, 'INTERMEDIATE', 25, 8, 'DRAFT', 0, true),
(120, 'java-21-features', 'Java 21 Features', 'Virtual threads, Record patterns, Sequenced collections', 6, 'ADVANCED', 25, 9, 'DRAFT', 0, true),
(121, 'virtual-threads', 'Virtual Threads', 'Loom lightweight threads mapping 1M concurrent operations to OS threads', 6, 'ADVANCED', 30, 10, 'DRAFT', 0, true),
(122, 'pattern-matching', 'Pattern Matching', 'Pattern matching for switch, record deconstruction', 6, 'ADVANCED', 20, 11, 'DRAFT', 0, true),
(123, 'sequenced-collections', 'Sequenced Collections', 'First/Last element access interfaces', 6, 'INTERMEDIATE', 15, 12, 'DRAFT', 0, true),
(124, 'records', 'Record Classes', 'Immutable data transfer objects with auto-generated constructor, equals, hashCode, toString', 6, 'BEGINNER', 15, 13, 'DRAFT', 0, true),

-- MODULE 7: Multithreading (125-136)
(125, 'process', 'Process', 'System-allocated memory space and execution program state', 7, 'BEGINNER', 10, 1, 'DRAFT', 0, true),
(126, 'thread', 'Thread', 'Lighter execution path within a shared process', 7, 'BEGINNER', 15, 2, 'DRAFT', 0, true),
(127, 'runnable', 'Runnable Interface', 'Defining task execution logic returning void', 7, 'BEGINNER', 10, 3, 'DRAFT', 0, true),
(128, 'callable', 'Callable Interface', 'Defining task execution returning parameterized result and throwing exceptions', 7, 'INTERMEDIATE', 15, 4, 'DRAFT', 0, true),
(129, 'executor-framework', 'Executor Framework', 'Separating thread creation, execution, and pooling', 7, 'INTERMEDIATE', 25, 5, 'DRAFT', 0, true),
(130, 'thread-pool', 'Thread Pools', 'Fixed, Cached, Scheduled thread pools, queue sizes, rejection policies', 7, 'ADVANCED', 25, 6, 'DRAFT', 0, true),
(131, 'synchronization', 'Synchronization', 'Monitor locks, synchronized keyword, reentrant locks, thread contention', 7, 'ADVANCED', 25, 7, 'DRAFT', 0, true),
(132, 'race-condition', 'Race Condition', 'Unpredictable output caused by concurrent modifications to shared state', 7, 'INTERMEDIATE', 20, 8, 'DRAFT', 0, true),
(133, 'deadlock', 'Deadlock', 'Circular lock dependency threads freeze, lock ordering strategies', 7, 'ADVANCED', 20, 9, 'DRAFT', 0, true),
(134, 'future', 'Future Interface', 'Representing asynchronous computational result wrapper', 7, 'INTERMEDIATE', 15, 10, 'DRAFT', 0, true),
(135, 'completable-future', 'CompletableFuture', 'Promise-style async orchestration pipelines with thenApply, thenCombine, allOf', 7, 'ADVANCED', 30, 11, 'DRAFT', 0, true),
(136, 'virtual-threads-concurrency', 'Virtual Threads Concurrency', 'Pinning problems, carrier threads, blocking tasks optimizations', 7, 'EXPERT', 30, 12, 'DRAFT', 0, true),

-- MODULE 8: SQL (137-160)
(137, 'sql-introduction', 'SQL Introduction', 'Relational database systems structure and SQL commands grouping', 8, 'BEGINNER', 15, 1, 'DRAFT', 0, true),
(138, 'select', 'SELECT Statement', 'Retrieving dataset records with filtering, limits, expressions', 8, 'BEGINNER', 10, 2, 'DRAFT', 0, true),
(139, 'insert', 'INSERT Statement', 'Writing new table rows, batch inserting, upsert configurations', 8, 'BEGINNER', 10, 3, 'DRAFT', 0, true),
(140, 'update', 'UPDATE Statement', 'Modifying existing rows, bulk updates, subquery updates', 8, 'BEGINNER', 10, 4, 'DRAFT', 0, true),
(141, 'delete', 'DELETE Statement', 'Removing rows, transactional safety, where clause importance', 8, 'BEGINNER', 10, 5, 'DRAFT', 0, true),
(142, 'create-table', 'CREATE TABLE', 'Creating relational tables, data types mapping', 8, 'BEGINNER', 15, 6, 'DRAFT', 0, true),
(143, 'alter-table', 'ALTER TABLE', 'Modifying database tables structures, index addition, data type changes', 8, 'INTERMEDIATE', 15, 7, 'DRAFT', 0, true),
(144, 'drop-table', 'DROP TABLE', 'Removing database objects permanently', 8, 'BEGINNER', 10, 8, 'DRAFT', 0, true),
(145, 'truncate', 'TRUNCATE Statement', 'High-performance reset table empty, direct data page drops', 8, 'INTERMEDIATE', 15, 9, 'DRAFT', 0, true),
(146, 'primary-key', 'Primary Key', 'Defining row identity, clustered indexing connection', 8, 'BEGINNER', 15, 10, 'DRAFT', 0, true),
(147, 'foreign-key', 'Foreign Key', 'Referential integrity, cascade options', 8, 'BEGINNER', 15, 11, 'DRAFT', 0, true),
(148, 'constraints', 'Database Constraints', 'Unique, Not Null, Check constraints, default fields validation', 8, 'BEGINNER', 15, 12, 'DRAFT', 0, true),
(149, 'index', 'Database Index', 'B-Tree data structures, indexing pros/cons, cardinallity', 8, 'INTERMEDIATE', 25, 13, 'DRAFT', 0, true),
(150, 'clustered-index', 'Clustered Index', 'Physical table row sort alignment by key', 8, 'ADVANCED', 20, 14, 'DRAFT', 0, true),
(151, 'non-clustered-index', 'Non-Clustered Index', 'Secondary logical indexes pointing to row addresses', 8, 'ADVANCED', 20, 15, 'DRAFT', 0, true),
(152, 'join', 'Joins', 'Inner, Left, Right, Full outer joins, cartesian cross joins', 8, 'BEGINNER', 20, 16, 'DRAFT', 0, true),
(153, 'group-by', 'GROUP BY Statement', 'Aggregating rows (Sum, Count, Avg, Min, Max) into dataset groups', 8, 'INTERMEDIATE', 15, 17, 'DRAFT', 0, true),
(154, 'having', 'HAVING Clause', 'Filtering aggregated groups post aggregation processing', 8, 'INTERMEDIATE', 15, 18, 'DRAFT', 0, true),
(155, 'order-by', 'ORDER BY Statement', 'Sorting outputs, ascending vs descending, null placement', 8, 'BEGINNER', 10, 19, 'DRAFT', 0, true),
(156, 'limit', 'LIMIT & OFFSET', 'Paging dataset outputs, optimization strategies for offset offsets', 8, 'BEGINNER', 15, 20, 'DRAFT', 0, true),
(157, 'acid', 'ACID Transactions', 'Atomicity, Consistency, Isolation levels, Durability properties', 8, 'ADVANCED', 30, 21, 'DRAFT', 0, true),
(158, 'normalization', 'Normalization', 'Reducing data anomalies, normal forms (1NF, 2NF, 3NF, BCNF)', 8, 'INTERMEDIATE', 25, 22, 'DRAFT', 0, true),
(159, 'views', 'Views', 'Stored query projections, materialized views performance benefits', 8, 'INTERMEDIATE', 20, 23, 'DRAFT', 0, true),
(160, 'stored-procedures', 'Stored Procedures', 'Database-side precompiled execution code blocks, functions vs procedures', 8, 'ADVANCED', 25, 24, 'DRAFT', 0, true),

-- MODULE 9: JVM Internals (161-175)
(161, 'jvm-architecture', 'JVM Architecture', 'Class Loaders, Memory Areas, JIT Compiler, Garbage Collector layers', 9, 'INTERMEDIATE', 25, 1, 'DRAFT', 0, true),
(162, 'class-loader', 'Class Loader Subsystem', 'Loading, Linking, Initialization stages, Bootstrap, Platform, App class loaders', 9, 'ADVANCED', 25, 2, 'DRAFT', 0, true),
(163, 'execution-engine', 'Execution Engine', 'JIT Compiler, Interpreter, Profiler, GC integration', 9, 'ADVANCED', 20, 3, 'DRAFT', 0, true),
(164, 'memory-areas', 'JVM Memory Areas', 'Heap, Stack, Metaspace, PC Register, Native Method Stack divisions', 9, 'INTERMEDIATE', 25, 4, 'DRAFT', 0, true),
(165, 'heap', 'Heap Memory', 'Java Object allocation area, Eden, Survivor S0/S1, Tenured generations', 9, 'INTERMEDIATE', 20, 5, 'DRAFT', 0, true),
(166, 'stack-memory', 'Stack Memory', 'Thread-private frame allocations, local variables, method call trace', 9, 'INTERMEDIATE', 15, 6, 'DRAFT', 0, true),
(167, 'metaspace', 'Metaspace', 'Off-heap class metadata, dynamic resizing replacement of PermGen', 9, 'ADVANCED', 15, 7, 'DRAFT', 0, true),
(168, 'pc-register', 'Program Counter Register', 'Tracking thread execution instructions pointer', 9, 'BEGINNER', 10, 8, 'DRAFT', 0, true),
(169, 'native-method-stack', 'Native Method Stack', 'Allocations for JNI / C-level system calls', 9, 'INTERMEDIATE', 10, 9, 'DRAFT', 0, true),
(170, 'jit-compiler', 'JIT Compiler', 'Just-In-Time native code compilation, profiling, hot methods optimization', 9, 'ADVANCED', 25, 10, 'DRAFT', 0, true),
(171, 'garbage-collection', 'Garbage Collection', 'Tracing gc, roots, mark-sweep-compact algorithms', 9, 'ADVANCED', 25, 11, 'DRAFT', 0, true),
(172, 'minor-gc', 'Minor GC (Scavenge)', 'Clearing Young generation objects, survival transitions', 9, 'INTERMEDIATE', 20, 12, 'DRAFT', 0, true),
(173, 'major-gc', 'Major GC (Full GC)', 'Clearing Old/Tenured memory, application pauses (STW)', 9, 'ADVANCED', 25, 13, 'DRAFT', 0, true),
(174, 'g1-gc', 'G1 Garbage Collector', 'Region-based generational concurrent collector, pause-time goals', 9, 'ADVANCED', 30, 14, 'DRAFT', 0, true),
(175, 'zgc', 'ZGC (Z Garbage Collector)', 'Ultra-low pause time sub-millisecond concurrent collector', 9, 'EXPERT', 35, 15, 'DRAFT', 0, true),

-- MODULE 10: Core Java (176-192)
(176, 'jdk', 'JDK', 'Java Development Kit compiler, tools, and JRE bundles', 10, 'BEGINNER', 10, 1, 'DRAFT', 0, true),
(177, 'jre', 'JRE', 'Java Runtime Environment JVM, libraries, core files', 10, 'BEGINNER', 10, 2, 'DRAFT', 0, true),
(178, 'jvm-overview', 'JVM Overview', 'Virtual machine execution layer and cross-platform bytecode execution', 10, 'BEGINNER', 10, 3, 'DRAFT', 0, true),
(179, 'string', 'String Class', 'Immutable char array, String Constant Pool, garbage collection behavior', 10, 'BEGINNER', 20, 4, 'DRAFT', 0, true),
(180, 'string-builder', 'StringBuilder', 'Mutable sequence of characters, non-synchronized fast execution', 10, 'BEGINNER', 15, 5, 'DRAFT', 0, true),
(181, 'string-buffer', 'StringBuffer', 'Mutable sequence of characters, synchronized thread-safe legacy class', 10, 'BEGINNER', 15, 6, 'DRAFT', 0, true),
(182, 'equals-method', 'equals() method', 'Implementing logical object equality checks', 10, 'BEGINNER', 15, 7, 'DRAFT', 0, true),
(183, 'double-equals', '== operator', 'Comparing reference addresses vs primitive values directly', 10, 'BEGINNER', 10, 8, 'DRAFT', 0, true),
(184, 'hash-code', 'hashCode() contract', 'Hashing key, bucket placement, equals-hashCode consistency rule', 10, 'INTERMEDIATE', 20, 9, 'DRAFT', 0, true),
(185, 'exception', 'Exception Handling', 'Try, Catch, Finally, Throw, Throws hierarchy, call stack unwinding', 10, 'BEGINNER', 20, 10, 'DRAFT', 0, true),
(186, 'checked-exception', 'Checked Exception', 'Compile-time enforced exception handling subclasses of Exception', 10, 'BEGINNER', 15, 11, 'DRAFT', 0, true),
(187, 'unchecked-exception', 'Unchecked Exception', 'Runtime exceptions subclasses of RuntimeException (NPE, ArrayIndex)', 10, 'BEGINNER', 15, 12, 'DRAFT', 0, true),
(188, 'serialization', 'Serialization', 'Saving object state to byte streams, serialVersionUID contract', 10, 'INTERMEDIATE', 25, 13, 'DRAFT', 0, true),
(189, 'transient', 'transient keyword', 'Excluding fields from serialization flow', 10, 'INTERMEDIATE', 15, 14, 'DRAFT', 0, true),
(190, 'volatile', 'volatile keyword', 'Thread memory visibility, preventing CPU cache reads', 10, 'ADVANCED', 25, 15, 'DRAFT', 0, true),
(191, 'final-keyword', 'final keyword', 'Immutable variables, final classes (non-extendable), final methods (non-overridable)', 10, 'BEGINNER', 15, 16, 'DRAFT', 0, true),
(192, 'static-keyword', 'static keyword', 'Class-level variables, methods, class initialization blocks, memory allocation in Metaspace', 10, 'BEGINNER', 15, 17, 'DRAFT', 0, true)
ON CONFLICT (id) DO UPDATE SET 
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    module_id = EXCLUDED.module_id,
    difficulty = EXCLUDED.difficulty,
    estimated_minutes = EXCLUDED.estimated_minutes,
    display_order = EXCLUDED.display_order;

-- Adjust sequence for topics ID
SELECT setval('topics_id_seq', (SELECT MAX(id) FROM topics));
